list1 = []
list1.append(input("What is your name"))
print("Hello %s." % list1[0])
print("Your going to help me finish my essay")
print()
list1.append(input("Give me a verb?"))
print("A hero %s up for anyone they don’t judge they help." % list1[1])
list1.append(input("Give me another Verb?"))
print("%s stand up for what they believe in." % list1[2])
print()
list1.append(input("Give me a Noun"))
print()
list1.append(input("Give me a Adjective"))
print("A hero would do anything to %s up for what believe in he or she would %s himself or herself for the better." % (list1[3], list1[4]))
print()
list1.append(input("Give me an Noun"))
list1.append(input("Give me another Noun"))
list1.append(input("give me An Adjective"))
print("%s went to elsewhere to free the memories and save %s." % (list1[5], list1[6]))
print("Hero's do things what they think is right for someone or %s." % (list1[7]))
